language: go

branches:
  only:
    - "master"
go:
  - 1.10
  - 1.9
  - 1.8

env:
  - GOOS=linux
  - GOOS=darwin
  - GOOS=windows

script:
  - go get -u -t ./...

notifications:
  email:
    on_success: never
    on_failure: never
